[package]
name = "mariadb-proxy"
version = "0.1.0"
authors = ["Raymond Cheng <me@raymondcheng.net>"]
edition = "2018"

[dependencies]
byteorder = "1.0"
env_logger = "0.7"
futures = "0.3"
log = "0.4"
proper = "0.1"
tokio = { version = "0.2", features = ["full"] }

[dev-dependencies]
abci = "0.6"
mysql_async = "0.21"
sqlparser = "0.5"
